spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1

  h2:
    console:
      path: /h2-console
      enabled: 'true'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect